version: '3.9'
networks:
  shortlen:
    driver: bridge

services:
#  redis:
#    image: redis
#    container_name: 'redis-shortlen'
#    restart: unless-stopped
#    ports:
#      - "127.0.0.1:6380:6379"

  php:
    container_name: 'php-shortlen'
    networks:
      - shortlen
    build:
      context: ./docker/php
    volumes:
      - '.:/var/www/html'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
    working_dir: '/var/www/html'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx:
    container_name: 'nginx-shortlen'
    image: nginx:1.23.2-alpine
    networks:
      - shortlen
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf'

  postgres:
    container_name: 'pg-shortlen'
    image: postgres:15-alpine
    networks:
      - shortlen
    ports:
      - '127.0.0.1:5433:5432'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgresql:/var/lib/postgresql/data:rw'
volumes:
  postgresql: