<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240311120241 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE url (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_url VARCHAR(7) NOT NULL, long_url TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('DROP TABLE url');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SCHEMA url-schema');
        $this->addSql('CREATE TABLE url-schema.url (id INT NOT NULL, shorturl VARCHAR DEFAULT NULL, longurl VARCHAR DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('DROP TABLE url');
    }
}
